### ISSUE TITLE
Circle CICD is failing

### ISSUE THREAD

**Issue by doublethefish** [alendit/sphinx-pyreverse#20]
This needs looking into, at some point.

**Comment by doublethefish** [comment]
CICD is now fixed on my fork, but I need settings access to update them here.

**Comment by Nic30** [comment]
Hello,

I am not sure what is wrong with `circleci/python:latest` but `circleci/python@0.2.1` works
https://app.circleci.com/pipelines/github/Nic30/hdlConvertorAst/50/workflows/9ca82683-d7b1-417a-8298-a0f827ec1c56/jobs/51

Can we swap it so the tests are actually executed?

I think that this project does not work for modules which do have more than 3 levels of hierarchy, because PYTHONPATH or CWD are not set correctly for pyreverse.

https://readthedocs.org/projects/hdlconvertorast/builds/13513547/

It was working in some previous version but before fixing this issue can we please get CI working?

**Comment by doublethefish** [comment]
I don’t think your issue is related to ci/cd failing(?).

IIRC the CI/CD issue is a keys issue.

**Comment by Nic30** [comment]
@doublethefish , no it is not, but I can not help you to fix the potential issue unless the CI is working. I am not sure if it an issue on your side, but I just wanted to tell you that the mentioned `circleci/python@0.2.1` image works reliably.
(I tried to give you hint how to fix CI, think of it my issue is not important now, let's fix CI.)

**Comment by doublethefish** [comment]
@Nic30 your issue relates to a regression in 
`astroid`, a library used by `pyreverse`. That has been reported to the maintainers there.

`sphinx-pyreverse=>v0.0.16` is pinned to a working astroid version. If you update and/or pin to the same version of astroid you should be ok.

**Comment by Nic30** [comment]
> That has been reported to the maintainers there.

nice, thank you, I have seen there was some problem, can you send me a link on issue somehow?

**Comment by doublethefish** [comment]
@Nic30  if you’d read my report here _properly_ you could see that on my fork the CI/CD is passing... no need tp get snippy. I hope my comment helps you fix your issue.

**Comment by doublethefish** [comment]
> > That has been reported to the maintainers there.
> 
> nice, thank you, I have seen there was some problem, can you send me a link on issue somehow?

sure thing.

**Comment by doublethefish** [comment]
Please see #25 pyreverse fails with "module cannot be found" for links & more info.

#25 is your original issue that duped this issue, and I've updated it to match the issue shown by your logs (fixed by fedd84e and in v.0.016).

I hope that helps :)

**Comment by Nic30** [comment]
thank you again
