### ISSUE TITLE
More documentation, and/or host your own documentation site for the extension using github pages to showcase a comprehensive example

### ISSUE THREAD

**Issue by guillaume-chevalier** [alendit/sphinx-pyreverse#33]
Related: #31 

I tried to make it work a lot. And I am familiar with sphinx, having built [Neuraxle](https://www.neuraxle.org/stable/intro.html). 

Getting errors like: 
```
Exception occurred:
  File "/home/gui/Documents/GIT/www.neuraxle.org-builder/venv/lib/python3.6/site-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/gui/Documents/GIT/www.neuraxle.org-builder/docs/uml_images/packages_neuraxle.base.png'
The full traceback has been saved in /tmp/sphinx-err-5kgw4ghc.log, if you want to report the issue to the developers.
```

And the `/tmp/sphinx-err-5kgw4ghc.log` file doesn't exist.

**Comment by patou01** [comment]
I second this. The package seems useful, but I cannot for the life of me get anything basic out of it. I sort of suck with the whole sphinx/rST/pyreverse thing, but there's a decent chance that a number of noobs come across your package and... go away.

Something as straightforward as the equivalent of the two calls
`pyreverse my_module.py -c ClassA`
`pyreverse my_module.py -c ClassB` 

I would expect it to become

```
.. uml:: my_module
    :classes: ClassA
``` 
and

```
.. uml:: my_module
    :classes: ClassB
``` 
Both of which raise an exception
```
uml_generate_directive.py", line 55, in _validate
    raise ValueError(
ValueError: invalid flags encountered: {'ClassA'}. Must be one of {':packages:', ':classes:'}
```

It *seems* I should then set `sphinx_pyreverse_class = "ClassA"` in `conf.py` but why would this be the only UML I want to generate ever in a document? Or should I modify it everytime to some sort of array when I want to add a graph?

I would expect a somewhat similar approach as `autodoc` which is like this
```
.. autoclass:: Noodle
   :members: eat
   :private-members: +_spicy, _garlickly
```
and not defining `members = "eat"` and `private_members = ["_spicy", "_garlickly"]` in `conf.py`.

Similarly, I can understand having a global config for other parameters, but a local override would make sense for some at least (ancestors and associates).

But maybe I haven't understood the goal of this package.

**Comment by patou01** [comment]
> What is the `pyreverse` command that Sphinx invokes? ([how](https://github.com/alendit/sphinx-pyreverse#troubleshooting))

I think you're taking things in reverse ( :) ) here. The question should be: If a user wanted to add the output of  ``pyreverse my_module.py -c ClassA -o png`` (but we can ignore -o png here) at the point of the command in their rST file, how should they proceed?
There's no pyreverse command, since sphinx-pyreverse throws before that. The only way I can get sphinx-pyreverse to output anything is by using
```
.. uml:: my_module
    :classes: 
```

which then makes 
`pyreverse --output png --project my_module my_module` , but that doesn't help me, since I want to run ``pyreverse my_module.py -c ClassA -o png`` (or ClassB, both should be possible at any time in the document)


If one defines `sphinx_pyreverse_class = "ClassA"` then we get `pyreverse --output png --project my_module --class ClassA` which is probably close enough, but then the question becomes how do I modify `conf.py` during runtime, which does *not* sound like something that is a configuration.

**Comment by doublethefish** [comment]
This issue, #33, is for possible improvements to the docs, not a place for new feature requests. 

> The only way I can get sphinx-pyreverse to output anything is by using [snip]

Yes, that is the correct 👏 use of sphinx-pyreverse, as it is designed, and is documented fairly clearly thus (?🤔).

How do you find the documentation? Is it inaccurate in any way? They should be currently accurate as to what `sphinx-pyreverse` actually does. As you mention `-o`, have you read them and seen `sphinx_pyreverse_output` and `sphinx_pyreverse_only_classnames`, etc.?

If do you want other features either:
 1. submit a PR 👍
 2. create a detailed new issue for each specific feature you want, and perhaps some enterprising user will implement it for you, if you're unable to.

As this thread is now off-topic and @[guillaume-chevalier](https://github.com/guillaume-chevalier) didn't feel it important enough to respond to my request for more info/an example, I'm closing this.
